### ISSUE TITLE
ConnectionError in connect command

### ISSUE THREAD

**Issue by joshed-io** [phrawzty/ubunolia#1]
Getting an error when I try to connect to the server:

```
AlgoliaException: Unreachable hosts: {'PBF4ZR3KBT-2.algolianet.com': "ConnectionError: HTTPSConnectionPool(host='PBF4ZR3KBT-2.algolianet.com', port=443): Max retries exceeded with url: /1/indexes/ubuntu_irc_logs/query
```

Has the Algolia app where the data is located changed?

**Comment by phrawzty** [comment]
The account was a trial plan which expired; the app went along with it. Luckily, it's trivial to set up a new data source (the import scripts are in `utils/`).
